server:
  port: 8888

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 1032
        max-idle: 0
xx:
  redis:
    queue:
      topic: dog
      thread-num: 1000
      core-pool-size: 19
      maximum-pool-size: 19
      keep-alive-time: 30
      queue-size: 4096
